<<<<<<< Updated upstream
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./(shared)/Navbar";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Roboblog",
  description: "This app uses AI",
};
=======
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
>>>>>>> Stashed changes

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<<<<<<< Updated upstream
      <body className={openSans.className}>
        <Navbar/>
        {children}
      </body>
=======
      <body>{children}</body>
>>>>>>> Stashed changes
    </html>
  )
}
